alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: missionmed-backend
    match:
      path:
        prefix: /
name: missionmed-backup-deploy1
region: blr
services:
- build_command: composer install
  environment_slug: php
  envs:
  - key: APP_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  github:
    branch: master
    deploy_on_push: true
    repo: missionmed/missionmed-backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  name: missionmed-backend
  run_command: |-
    cp .env.example .env
    php artisan key:generate
    heroku-php-apache2 public/
  source_dir: /
workers:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: YogeshBhatt/docker-cron
  instance_count: 1
  instance_size_slug: professional-xs
  name: dockercron
  source_dir: /
